# Generated by Django 3.1.7 on 2021-04-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('customer', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercheque',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercheque',
            name='supplierpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.supplierpayment'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='customercheque',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='customercheque',
            name='customerpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.customerpayment'),
        ),
    ]
