# Generated by Django 3.1.7 on 2021-08-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210406_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Versement', 'Versement')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Versement', 'Versement')], default='Cash', max_length=10),
        ),
    ]
