# Generated by Django 3.1.7 on 2021-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210807_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
