# Generated by Django 3.1.7 on 2021-04-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('ref', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('buyprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price1', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price2', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price3', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price4', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price5', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('price6', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('alert_quantity', models.PositiveIntegerField(default=1)),
                ('box_quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='product.product')),
            ],
        ),
    ]
