# Generated by Django 3.1.7 on 2021-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price6',
        ),
        migrations.AddField(
            model_name='producttype',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='price5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='price6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
