# Generated by Django 3.1.7 on 2021-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210411_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alert_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='box_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buyprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='producttype',
            name='alert_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producttype',
            name='box_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producttype',
            name='buyprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
