# Generated by Django 3.1.7 on 2021-10-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_buyorderitem_orderitem_sellerbuyorder_sellersellorder_sellerstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorderitem',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='sellerbuyorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellerbuyorder',
            name='delivered',
        ),
    ]
