# Generated by Django 3.1.7 on 2021-10-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20211011_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_type', to='seller.sellerstock'),
        ),
    ]
