# Generated by Django 3.1.7 on 2021-10-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210710_2017'),
        ('seller', '0004_auto_20211011_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_stock', to='warehouse.stock'),
        ),
    ]
