# Generated by Django 3.1.7 on 2021-10-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20211012_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='in_hold_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
