# Generated by Django 3.1.7 on 2021-10-13 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
        ('category', '0001_initial'),
        ('seller', '0006_seller_in_hold_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerStockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttype')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerstock')),
            ],
            options={
                'verbose_name': 'seller stock product',
                'verbose_name_plural': 'seller stock products',
                'ordering': ('product',),
            },
        ),
    ]
