# Generated by Django 3.1.7 on 2021-12-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_sellerstockproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_type', models.CharField(blank=True, choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4'), ('type5', 'type5'), ('type6', 'type6')], default='type1', max_length=9)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sellersellorder',
            name='customer_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.sellercustomer'),
        ),
    ]
