# Generated by Django 3.1.7 on 2021-12-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20211221_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersellorder',
            name='customer',
        ),
    ]
