# Generated by Django 3.1.7 on 2021-12-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_remove_sellersellorder_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellersellorder',
            old_name='customer_seller',
            new_name='customer',
        ),
    ]
