# Generated by Django 3.1.7 on 2021-12-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_sellersellorder_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersellorder',
            name='seller',
        ),
        migrations.AddField(
            model_name='sellercustomer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
    ]
