# Generated by Django 3.1.7 on 2022-01-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210411_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0012_auto_20211221_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoStockSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('in_hold_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.city')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
