# Generated by Django 3.1.7 on 2022-02-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_sellermoneyinhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercustomerpayment',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller'),
        ),
    ]
