# Generated by Django 3.1.7 on 2021-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='type',
            new_name='prod_type',
        ),
    ]
