# Generated by Django 3.1.7 on 2021-04-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210420_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='prod_type',
            new_name='type',
        ),
    ]
