# Generated by Django 3.1.7 on 2021-04-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('billingorder', '0001_initial'),
        ('buyorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbilling_item', to='order.order'),
        ),
        migrations.AddField(
            model_name='billbuyorderitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billingorder.buyorderbilling'),
        ),
        migrations.AddField(
            model_name='billbuyorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbilling_item', to='buyorder.buyorder'),
        ),
    ]
