# Generated by Django 3.1.7 on 2021-04-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyorder', '0002_buyorderitem_product'),
        ('order', '0002_auto_20210406_1038'),
        ('billingorder', '0002_orderbilling_delivery'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderbilling',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='billorderitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billingorder.orderbilling'),
        ),
        migrations.AddField(
            model_name='billorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbilling_item', to='order.order'),
        ),
        migrations.AddField(
            model_name='billbuyorderitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billingorder.buyorderbilling'),
        ),
        migrations.AddField(
            model_name='billbuyorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderbilling_item', to='buyorder.buyorder'),
        ),
    ]
