# Generated by Django 3.1.7 on 2021-07-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210411_1223'),
        ('billingorder', '0002_auto_20210426_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbilling',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
