# Generated by Django 3.1.7 on 2021-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_name', models.CharField(max_length=200, null=True, verbose_name='Transaction Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_date', models.DateField(blank=True, null=True, verbose_name='Transaction Date')),
                ('Transaction_type', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=8, verbose_name='Transaction Type')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Transaction Date')),
            ],
        ),
    ]
