# Generated by Django 3.1.7 on 2021-04-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('buyorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyorder_item', to='product.product'),
        ),
    ]
