# Generated by Django 3.1.7 on 2021-04-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyorder', '0002_buyorderitem_product'),
        ('customer', '0001_initial'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock'),
        ),
        migrations.AddField(
            model_name='buyorderitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttype'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
